name: Deploy Pong Game

on:
  push:
    branches:
      - main   # change if your branch is master

permissions:
  contents: write   # required for gh-pages deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Validate HTML
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -qe index.html || true

      - name: Validate CSS
        run: npx stylelint "**/*.css" --no-error-on-unmatched-pattern || true

      - name: Validate JS
        run: npx eslint "**/*.js" --no-error-on-unmatched-pattern || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,.gitignore'
