name: Deploy Pong Game

on:
  push:
    branches:
      - main   # change to master if that's your default branch

permissions:
  contents: write   # required for gh-pages deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # keep ./ if index.html is in root, change if in "public" or "docs"
